name: Build & Deploy Docs
on:
  push:
    branches: [ main ]
    paths: [ 'docs/**', '.github/workflows/pages.yml' ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ① Jekyll で Markdown→HTML
      - uses: actions/jekyll-build-pages@v1     # 公式アクション
        with:
          source: ./docs                        # 元フォルダ
          destination: ./_site                  # 出力先

      # ② Pages 用 Artifact にアップロード
      - uses: actions/upload-pages-artifact@v3
        with: { path: ./_site }

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v4
